{
 "title": "Concert Booking MVP",
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Reservation Success Rate",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(reservation_total{result=\"success\"}[1m])) / clamp_min(sum(rate(reservation_total[1m])), 1)"
    }
   ]
  },
  {
   "title": "Failed Reservation",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "rate(failed_reservation_total[1m])"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 8 },
   "targets": [
    { "expr": "kafka_consumer_lag" }
   ]
  },
  {
   "title": "Redis Memory (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 8, "w": 8, "h": 8 },
   "targets": [
    { "expr": "redis_memory_bytes" }
   ]
  },
  {
   "title": "DB Open Connections",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 8, "w": 8, "h": 8 },
   "targets": [
    { "expr": "db_open_connections" }
   ]
  }
 ]
}